# Generated by Django 6.0.2 on 2026-03-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
